/*
 * forum
 *
 * Тестовое задание для реализации проекта \"Форумы\" на курсе по базам данных в Технопарке Mail.ru (https://park.mail.ru).
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"tpark_db/router"
)

func main() {
	log.Printf("Server started")

	router := router.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
