TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE forums CASCADE;
TRUNCATE TABLE threads CASCADE;
TRUNCATE TABLE votes CASCADE;
TRUNCATE TABLE posts CASCADE;
TRUNCATE TABLE errors CASCADE;

-- DELETE FROM forums;
-- DELETE FROM threads;
-- DELETE FROM votes;
-- DELETE FROM posts;
-- DELETE FROM errors;